name: Create release pull request

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: yarn changeset version && yarn pre-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
