name: Verify
on:
  workflow_call:
  workflow_dispatch:

jobs:
  pre-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Pre-Build package
        run: yarn run changeset:prepublish
